"""Added Product Categories

Revision ID: 955021727835
Revises: f3c4e0476119
Create Date: 2023-05-26 17:22:36.307087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955021727835'
down_revision = 'f3c4e0476119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.drop_column('stock_quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_quantity', sa.INTEGER(), nullable=True))
        batch_op.drop_column('category_id')

    op.drop_table('categories')
    # ### end Alembic commands ###
